local Language = {}

Language.es = {
	--header
	headerMap = "CERCANOS",
	headerTray = "MI BANDEJA",
	headerDownloads = "MIS DESCARGAS",
	headerSearcher = "BUSCADOR",
	headerTxt1 = "DEAL Descargado",
	headerTxt2 = "Consulta tus descargas",
	headerTxt1Share = "DEAL Compartido",
	headerTxt2Share = "Se envio el Deal a tu amigo",
	headerTxt1Reedem = "DEAL Redimido",
	headerTxt2Reedem = "No olvides consultar otros Deals que tenemos para ti.",
	headerSaveBeaconMSG1 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerSaveBeaconMSG2 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerSaveBeaconMSG3 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerGetLoadingTitle = "Cargando, por favor espere...",
	headerTxtWifiBLE = "Para obtener mejores beneficios active su Wifi y/o bluetooth",
	headerTxtReturn = "REGRESAR",
	--home
	homeInicio = "INICIO",
	homeEvent = "EVENTOS",
	homeDeals = "DEALS",
	homeNoFilterEvent = "Eventos con el filtro no disponible",
	homeNoFilterDeals = "Deals con el filtro no disponible",
	homeNoConection = "¡conexión no disponible, intentelo de nuevo!",
	--buildRow
	buildMSGOf = "De: ",
	buildMSGSubject = "Asunto: ",
	buildDownloads = "DESCARGADO",
	buildRedeemed = "REDIMIDO",
	buildShared = "COMPARTIDO",
	buildAvailable = " Disponibles",
	buildHighlight = " DEAL DESTACADO",
	--deals
	dealsTEXTA1 = "* O activa tu bluetooth y solicita al comercio su dispositivo GO",
	dealsTEXTA2 = "* O solicita al comercio su dispositivo GO",
	dealsTEXTB1 = "* Activa tu bluetooth y acerca tu teléfono al dispositivo GO",
	dealsTEXTB2 = "* Acerca tu teléfono al dispositivo GO",
	dealsTitleInfo = "Deal redimido",
	dealsInfo = "No olvides consultar los otros Deals que ",
	dealsInfo2 = " te ofrece.",
	dealstxtBtn = "DEAL REDIMIDO",
	dealsTxtCode = "CODIGO PARA CANJEAR",
	dealsTxtInfoRedimir  = "* Proporciona este código al comercio para hacer válido tu Deal",
	dealsTxtRed = "CONTINUAR",
	dealsTxtTitleInfoDow = "Redime este Deal!",
	dealsTxtInfoDow = "Deja presionado el botón mientras lo acercas a nuestro dispositivo GO> ",
	dealsTxtInfoDow2 = "disponible en todos los establecimientos afiliados. PREGUNTA POR EL!",
	dealsTxtBtnDow = "REDIMIR DEAL",
	dealsTitleInfoShare = "Ha compartido este deals!",
	dealstxtBtnShare = "DEAL COMPARTIDO",
	dealsTxtTotalDeals = " Deals",
	dealsTxtBtnComer = "COMPARTIR DEAL",
	dealsTxtBtnComer2 = "IR A COMERCIO",
	dealsTxtBtnDowCre = "DESCARGAR DEAL",
	dealsTxtTitleInfoInterest = "¿Te interesa este Deal?",
	dealsTxtInfoWallet = "No lo pienses más y descárgalo, ",
	dealsTxtInfoWallet2 = "se guardará en tu cartera para que lo uses en tu próxima visita.",
	dealsTxtValidity = "Vigencia: ",
	dealsTxtAdditionalInformation = "Informacion Adicional: ",
	dealsTxtTitleInfoDS = "Deal compartido",
	dealsTxtInfoDS = "No olvides consultar los otros Deals que ",
	dealsTxtInfoDS2 = " te ofrece.",
	dealsTxtTitleInfoTired= "Lo sentimos.",
	dealsTxtInfoTired = "Este Deal se ha agotado, pero no te preocupes ",
	dealsTxtBtnTired2 = " y el equipo de GoDeals tienen mas promociones para ti!",
	dealsTxtBtnTired= "AGOTADO",
	--event
	eventTxtGeneralInformacion = "Información Adicional: ",
	eventTxtAdditionalInformation = "Consultar ubicación en el mapa",
	--menu
	menuTxtMenu1 = "Tutorial",
	menuTxtMenu2 = "Configuración",
	menuTxtMenu3 = "Cerrar Sesión",
	menuTxtMenu4 = "Comercios Afiliados",
	menuTxtMenuCC = "Captura de código de regalo",
	menuTitleLeft = "CAMBIAR CIUDAD",
	--code
	codeTextErrorCode = "*Campo vacio. Ingrese un codigo de regalo",
	codeTxt1 = "Regalo envíado",
	codeTxt2 = "Consulta tu bandeja",
	codeTxtReedirCode = "Introduce el código de regalo",
	codeTxtBtnRC = "OBTENER REGALO",
	--friends
	friendFriendsTitle = "COMPARTIR DEAL CON:",
	friendTxtRefreshFriend = "Actualizar Amigos",
	friendTxtAceptF = "COMPARTIR DEAL",
	friendTxtCancelF = "CANCELAR",
	friendTxtSendEmailPlacer = "ENVIAR CORREO A UN AMIGO",
	--login
	loginNoNetworkConnection = "No se detecto conexión a internet.",
	loginCreateAlert1 = "El email y password son necesarios.",
	loginCreateAlert2 = "Los paswords no coinciden.",
	loginSignInAlert = "El email y password son necesarios.",
	loginTxtReturn1 = "Regresar",
	loginTxtDoSignIn = "Entrar",
	loginTxtReturn2 = "Regresar",
	loginTxtDoCreate = "Entrar",
	loginTxtCreate = "Crear Cuenta",
	loginTxtSignIn = "Entrar",
	--mensaje
	MSGTxtPartner0 = "De: ",
	MSGTxtTitle0= "Asunto: ",
	MSGxtBtnComer = "IR A COMERCIO",
	--Filter
	FilterNameEvent1 = "TODOS",
	FilterNameEvent2 = "CONCIERTOS",
	FilterNameEvent3 = "DEPORTIVOS",
	FilterNameEvent4 = "CULTURALES",
	FilterNameEvent5 = "ANIVERSARIOS",
	FilterNameEvent6 = "COMPRAS",
	FilterNameEvent7 = "OTROS",
	FilterNameDeals1 = "TODOS",
	FilterNameDeals2 = "RESTAURANTES",
	FilterNameDeals3 = "BARES",
	FilterNameDeals4 = "ANTROS",
	FilterNameDeals5 = "TURISMO",
	FilterNameDeals6 = "TECNOLOGIA",
	FilterNameDeals7 = "SERVICIOS",
	FilterNameDeals8 = "COMPRAS",
	FilterNameDeals9 = "OTROS",
	--notifications 
	notiGetNoContent = "En este momento no cuentas con notificaciones",
	--partner
	partnerTxtInfo6 = "DEALS disponibles",
	--partnerWelcome
	partnerWTxtPartner0 = "¡Bienvenido a ",
	partnerWTxtBtnComer = "VER MAS",
	--search
	searchTextSeparadorEventos = "Eventos y actividades.",
	searchTextSeparadorDeals = "Promociones para ti.",
	searchGetNoContent = "No hay resultados, intente con otra palabra",
	--wallet
	walletGetNoContent = "En este momento no cuentas con Deals descargados",
	walletTextSeparadorEventos = "ESTOS SON LOS DEALS DISPONIBLES EN TU CARTERA.",
	walletTextSeparadorRedimir = "ESTOS SON LOS DEALS REDIMIDOS.",
}

Language.en = {
	headerMap = "NEARBY",
	headerTray = "MY TRAY",
	headerDownloads = "MY DOWNLOADS",
	headerSearcher = "SEARCHER",
	headerTxt1 = "Downloaded DEAL",
	headerTxt2 = "Consult your downloads",
	headerTxt1Share = "Shared DEAL",
	headerTxt2Share = "Deal was sent to your friend",
	headerTxt1Reedem = "Redeemed DEAL",
	headerTxt2Reedem = "Do not forget to check other Deals we have for you.",
	headerSaveBeaconMSG1 = "Welcome, we have an offer for you today.",
	headerSaveBeaconMSG2 = "Welcome, we have an offer for you today.",
	headerSaveBeaconMSG3 = "Welcome, we have an offer for you today.",
	headerGetLoadingTitle = "Loading please wait ...",
	headerTxtWifiBLE = "For best benefits activate your WiFi and / or Bluetooth",
	headerTxtReturn = "BACK",
	--home
	homeInicio = "HOME",
	homeEvent = "EVENTS",
	homeDeals = "DEALS",
	homeNoFilterEvent = "Events with the filter unavailable",
	homeNoFilterDeals = "Deals with the filter unavailable",
	homeNoConection = "Connection is not available, try again!",
	--buildRow
	buildMSGOf = "Of: ",
	buildMSGSubject = "Subject",
	buildDownloads = "DOWNLOADED",
	buildRedeemed = "REDEEMED",
	buildShared = "SHARED",
	buildAvailable = " Available",
	buildHighlight = " DEAL HIGHLIGHTS",
	--deals
	dealsTEXTA1 = "* Or activate your bluetooth and requests to partner your device GO",
	dealsTEXTA2 = "* O requests to partner your GO device",
	dealsTEXTB1 = "* Activate your Bluetooth device on your phone GO",
	dealsTEXTB2 = "* About GO device to your phone",
	dealsTitleInfo = "Deal redeemed",
	dealsInfo = "Do not forget to check that the other Deals ",
	dealsInfo2 = " it offers you.",
	dealstxtBtn = "REDEEMED DEAL",
	dealsTxtCode = "CODE REDEMPTION",
	dealsTxtInfoRedimir  = "* Provides code to partner for your Deal valid",
	dealsTxtRed = "CONTINUE",
	dealsTxtTitleInfoDow = "Redeem this Deal!",
	dealsTxtInfoDow = "Holding down the button as you approach our GO device> ",
	dealsTxtInfoDow2 = " available at affiliated establishments. QUESTION BY!",
	dealsTxtBtnDow = "REDEEM DEAL",
	dealsTitleInfoShare = "He has shared this deals!",
	dealstxtBtnShare = "SHARE DEAL",
	dealsTxtTotalDeals = " Deals",
	dealsTxtBtnComer = "SHARE DEAL",
	dealsTxtBtnComer2 = "GO TO PARTNER",
	dealsTxtBtnDowCre = "DOWNLOAD DEAL",
	dealsTxtTitleInfoInterest = "Interested this Deal?",
	dealsTxtInfoWallet = "Do not hesitate and download it, ",
	dealsTxtInfoWallet2 = "it will be saved in your wallet for you to use on your next visit.",
	dealsTxtValidity = "validity: ",
	dealsTxtAdditionalInformation = "Additional Information: ",
	dealsTxtTitleInfoDS = "sharing Deal",
	dealsTxtTitleInfoTired= "We are sorry.",
	dealsTxtInfoTired = "This Deal is exhausted, but do not worry ",
	dealsTxtInfoTired2 = " GoDeals team and have more promotions for you!",
	dealsTxtBtnTired= "SOLD OUT",
	--event
	eventTxtGeneralInformacion = "Additional Information: ",
	eventTxtAdditionalInformation = "Check location on map",
	--
	--menu
	menuTxtMenu1 = "Tutorial",
	menuTxtMenu2 = "configuration",
	menuTxtMenu3 = "Close Session",
	menuTxtMenu4 = "Affiliate Partner",
	menuTxtMenuCC = "Capture gift code",
	menuTitleLeft = "CHANGE CITY",
	--code
	codeTextErrorCode = "* Empty field. Enter a code Gift",
	codeTxt1 = "Sent out gift",
	codeTxt2 = "Check your tray",
	codeTxtReedirCode = "Enter the code Gift",
	codeTxtBtnRC = "GET GIFT",
	--friends
	friendFriendsTitle = "SHARE DEAL WITH: ",
	friendTxtRefreshFriend = "Refresh Friends",
	friendTxtAceptF = "SHARE DEAL",
	friendTxtCancelF = "CANCEL",
	friendTxtSendEmailPlacer = "SEND MAIL TO A FRIEND",
	--login
	loginNoNetworkConnection = "No Internet connection is detected.",
	loginCreateAlert1 = "The email and password are required.",
	loginCreateAlert2 = "The paswords not match.",
	loginSignInAlert = "The email and password are required.",
	loginTxtReturn1 = "Return",
	loginTxtDoSignIn = "Enter",
	loginTxtReturn2 = "Return",
	loginTxtDoCreate = "Enter",
	loginTxtCreate = "Create Account",
	loginTxtSignIn = "Enter",
	--mensaje
	MSGTxtPartner0 = "Of: ",
	MSGTxtTitle0= "Subject: ",
	MSGxtBtnComer = "GO TO PARTNER",
	--Filter
	FilterNameEvent1 = "EVERYONE",
	FilterNameEvent2 = "CONCERTS",
	FilterNameEvent3 = "SPORTS",
	FilterNameEvent4 = "CULTURAL",
	FilterNameEvent5 = "ANNIVERSARIES",
	FilterNameEvent6 = "SHOPPING",
	FilterNameEvent7 = "OTHER",
	FilterNameDeals1 = "EVERYONE",
	FilterNameDeals2 = "RESTAURANTS",
	FilterNameDeals3 = "BARS",
	FilterNameDeals4 = "DENS",
	FilterNameDeals5 = "TOURISM",
	FilterNameDeals6 = "TECHNOLOGY",
	FilterNameDeals7 = "SERVICES",
	FilterNameDeals8 = "SHOPPING",
	FilterNameDeals9 = "OTHER",
	--notifications 
	notiGetNoContent = "At this point you do not have notifications",
	--partner
	partnerTxtInfo6 = "DEALS available",
	--partnerWelcome
	partnerWTxtPartner0 = "Welcome to",
	partnerWTxtBtnComer = "SEE MORE",
	--search
	searchTextSeparadorEventos = "Events and activities.",
	searchTextSeparadorDeals = "Promotions for you.",
	searchGetNoContent = "No results, try another word",
	--wallet
	walletGetNoContent = "At this point you do not have downloaded Deals",
	walletTextSeparadorEventos = "THESE ARE THE DEALS AVAILABLE IN YOUR WALLET.",
	walletTextSeparadorRedimir = "THESE ARE THE REDEEMED DEALS.",
	
	
}

return Language