local Language = {}

Language.es = {
	--header
	headerMap = "CERCANOS",
	headerTray = "MI BANDEJA",
	headerDownloads = "MIS DESCARGAS",
	headerSearcher = "BUSCADOR",
	headerTxt1 = "DEAL Canjeado",
	headerTxt2 = "Consulta tus canjes",
	headerTxt1Share = "DEAL Compartido",
	headerTxt2Share = "Se envio el Deal a tu amigo",
	headerTxt1Reedem = "DEAL Redimido",
	headerTxt2Reedem = "No olvides consultar otros Deals que tenemos para ti.",
	headerSaveBeaconMSG1 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerSaveBeaconMSG2 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerSaveBeaconMSG3 = "Bienvenido, hoy tenemos una oferta para ti.",
	headerGetLoadingTitle = "Cargando, por favor espere...",
	headerTxtWifiBLE = "Para obtener mejores beneficios active su Wifi y/o bluetooth",
	headerTxtReturn = "REGRESAR",
	--home
	homeInicio = "INICIO",
	homeEvent = "EVENTOS",
	homeDeals = "DEALS",
	homeNoFilterEvent = "Eventos con el filtro no disponible",
	homeNoFilterDeals = "Deals con el filtro no disponible",
	homeNoConection = "¡conexión no disponible, intentelo de nuevo!",
	homeNoItemsHome = "En estos momentos no hay Deals disponibles",
	homeNoItemsDeals = "En estos momentos no hay Deals disponibles",
	homeNoItemsEvents = "En estos momentos no hay Eventos disponibles",
	homeMoreItems = "Descubre mas Deals",
	--buildRow
	buildMSGOf = "De: ",
	buildMSGSubject = "Asunto: ",
	buildDownloads = "DESCARGAR",
	buildDownloadeds = "DESCARGADO",
	buildRedeemed = "REDIMIDO",
	buildShared = "COMPARTIDO",
	buildAvailable = " Disponibles",
	buildHighlight = " DEAL DESTACADO",
	--deals
	dealsTEXTA1 = "* O activa tu bluetooth y solicita al comercio su dispositivo GO",
	dealsTEXTA2 = "* O solicita al comercio su dispositivo GO",
	dealsTEXTB1 = "* Activa tu bluetooth y acerca tu teléfono al dispositivo GO",
	dealsTEXTB2 = "* Acerca tu teléfono al dispositivo GO",
	dealsTitleInfo = "Deal canjeado",
	dealsInfo = "No olvides consultar los otros Deals que ",
	dealsInfo2 = " te ofrece.",
	dealstxtBtn = "DEAL CANJEADO",
	dealsTxtCode = "CODIGO PARA CANJEAR",
	dealsTxtInfoRedimir  = "* Proporciona este código al comercio para hacer válido tu Deal",
	dealsTxtRed = "CONTINUAR",
	dealsTxtTitleInfoDow = "Redime este Deal!",
	dealsTxtInfoDow = "Deja presionado el botón mientras lo acercas a nuestro dispositivo GO> ",
	dealsTxtInfoDow2 = "disponible en todos los establecimientos afiliados. PREGUNTA POR EL!",
	dealsTxtBtnDow = "REDIMIR DEAL",
	dealsTitleInfoShare = "Ha compartido este deals!",
	dealstxtBtnShare = "DEAL COMPARTIDO",
	dealsTxtTotalDeals = " Deals",
	dealsTxtBtnComer = "COMPARTIR DEAL",
	dealsTxtBtnComer2 = "IR A COMERCIO",
	dealsTxtBtnDowCre = "¡USAR AHORA!",
	dealsTxtTitleInfoInterest = "¿Te interesa este Deal?",
	dealsTxtInfoWallet = "No lo pienses más y úsalo, ",
	dealsTxtInfoWallet2 = "deberas estar ubicado en las instalaciones del comercio.",
	dealsTxtValidity = "Vigencia: ",
	dealsTxtAdditionalInformation = "Informacion Adicional: ",
	dealsTxtTitleInfoDS = "Deal compartido",
	dealsTxtInfoDS = "No olvides consultar los otros Deals que ",
	dealsTxtInfoDS2 = " te ofrece.",
	dealsTxtTitleInfoTired= "Lo sentimos.",
	dealsTxtInfoTired = "Este Deal se ha agotado, pero no te preocupes ",
	dealsTxtBtnTired2 = " y el equipo de GoDeals tienen mas promociones para ti!",
	dealsTxtBtnTired= "AGOTADO",
    dealsTxtClose= "Regresar",
    dealsTxtNear = "Para canjear este Deal es necesario estar en las instalaciones del comercio",
    dealsTxtUse1 = "¿SEGURO QUE QUIERES USAR",
    dealsTxtUse2 = "ESTE DEAL AHORA?",
    dealsTxtConfirm = "USAR AHORA",
    dealsTxtBtnPerfilComer = "PERFIL DEL COMERCIO",
	--event
	eventTxtGeneralInformacion = "Información Adicional: ",
	eventTxtAdditionalInformation = "Consultar ubicación en el mapa",
	--menu
	menuTxtMenu1 = "Tutorial",
	--menuTxtMenu2 = "Configuración",
	menuTxtMenu2 = "Código Regalo",
	menuTxtMenu3 = "Cerrar Sesión",
	menuTxtMenu4 = "Comercios Afiliados",
	menuTxtMenuCC = "Captura de código de regalo",
	menuTitleLeft = "CAMBIAR CIUDAD",
	menuTitleLanguageLeft = "CAMBIAR IDIOMA",
	--code
	codeTextErrorCode = "*Campo vacio. Ingrese un codigo de regalo",
	codeTxt1 = "Regalo envíado",
	codeTxt2 = "Consulta tu bandeja",
	codeTxtReedirCode = "Introduce el código de regalo",
	codeTxtBtnRC = "OBTENER REGALO",
	--friends
	friendFriendsTitle = "COMPARTIR DEAL CON:",
	friendTxtRefreshFriend = "Actualizar Amigos",
	friendTxtAceptF = "COMPARTIR DEAL",
	friendTxtCancelF = "CANCELAR",
	friendTxtSendEmailPlacer = "ENVIAR CORREO A UN AMIGO",
	
	--login
	loginNoNetworkConnection = "No se detecto conexión a internet.",
	loginCreateAlert1 = "El email y password son necesarios.",
	loginCreateAlert2 = "Los paswords no coinciden.",
	loginSignInAlert = "El email y password son necesarios.",
	loginTxtReturn1 = "Regresar",
	loginTxtDoSignIn = "Entrar",
	loginTxtReturn2 = "Regresar",
	loginTxtDoCreate = "Entrar",
	loginTxtCreate = "Crear Cuenta",
	loginTxtSignIn = "Entrar",
    -- login2
    loginTitle1A = "CONSULTA LOS DEALS DISPONIBLES",
    loginTitle2A = "Y DESCARGA EL QUE TE INTERESE.",
    loginTitle3A = "¡SON GRATIS PERO LIMITADOS!",
    loginTitle4B = "ADEMÁS ¡OBTÉN REGALOS ADICIONALES ENCONTRANDO LOS",
    loginTitle5B = "CÓDIGOS DE REGALO EN LOS ANUNCIOS DE GO DEALS QUE VEAS",
    loginTitle6B = "A LO LARGO DE TU CIUDAD Y CON COMERCIOS AFILIADOS!",
    loginTitle4C = "¡Y CONSULTA LOS MEJORES EVENTOS DE TU CIUDAD",
    loginTitle5C = "PARA QUE SIEMPRE TENGAS ALGO NUEVO QUE HACER!",
    loginTitle6C = "",
    loginBtnFB = "CONECTARSE CON FACEBOOK",
    loginBtnEmail = "INGRESA CON USERNAME Ó EMAIL",
    loginBtnFree = "CONOCE MÁS DE LA APLICACIÓN",
    loginFreeMessages = "AQUÍ PODRÁS ENCONTRAR MENSAJES Y REGALOS ESPECIALES PARA TÍ DE PARTE DE NUESTROS COMERCIOS AFILIADOS",
    loginFreeDownloads = "CONSULTA AQUÍ TODOS LOS DEALS DESCARGADOS. ¡APURATE A OBTENERLOS! YÁ QUE SON LIMITADOS Y POR TIEMPO LIMITADO",
    loginFreeGiftCode = "AQUÍ PODRÁS INTRODUCIR TODOS LOS CÓDIGOS DE REGALO QUE ENCUENTRES EN TU CIUDAD. ¡OBTÉN CON ELLOS DEALS ÚNICOS!",
    loginFreeSign = "¡REGISTRATE AHORA!",
    loginDescUsername = "Email / Usuario",
    loginDescPasword = "Contraseña",
	--mensaje
	MSGTxtPartner0 = "De: ",
	MSGTxtTitle0= "Asunto: ",
	MSGxtBtnComer = "IR A COMERCIO",
	--Filter
	FilterNameEvent1 = "TODOS",
	FilterNameEvent2 = "CONCIERTOS",
	FilterNameEvent3 = "DEPORTIVOS",
	FilterNameEvent4 = "CULTURALES",
	FilterNameEvent5 = "ANIVERSARIOS",
	FilterNameEvent6 = "COMPRAS",
	FilterNameEvent7 = "OTROS",
	FilterNameDeals1 = "TODOS",
	FilterNameDeals2 = "RESTAURANTES",
	FilterNameDeals3 = "BARES",
	FilterNameDeals4 = "ANTROS",
	FilterNameDeals5 = "TURISMO",
	FilterNameDeals6 = "TECNOLOGIA",
	FilterNameDeals7 = "SERVICIOS",
	FilterNameDeals8 = "COMPRAS",
	FilterNameDeals9 = "OTROS",
	--notifications 
	notiGetNoContent = "En este momento no cuentas con notificaciones",
	--partner
	partnerTxtInfo6 = "DEALS disponibles",
	--partnerWelcome
	partnerWTxtPartner0 = "¡Bienvenido a ",
	partnerWTxtBtnComer = "VER MAS",
	--search
	searchTextSeparadorEventos = "Eventos y actividades.",
	searchTextSeparadorDeals = "Promociones para ti.",
	searchGetNoContent = "No hay resultados, intente con otra palabra",
	--wallet
	walletGetNoContent = "En este momento no cuentas con Deals descargados",
	walletTextSeparadorEventos = "ESTOS SON LOS DEALS DISPONIBLES EN TU CARTERA.",
	walletTextSeparadorRedimir = "ESTOS SON LOS DEALS REDIMIDOS.",
}

Language.en = {
	headerMap = "NEARBY",
	headerTray = "INBOX",
	headerDownloads = "MY DEALS",
	headerSearcher = "SEARCH",
	headerTxt1 = "DEAL Redem",
	headerTxt2 = "View your redemtions",
	headerTxt1Share = "Shared DEAL",
	headerTxt2Share = "Deal was sent to your friend",
	headerTxt1Reedem = "DEAL Redeemed",
	headerTxt2Reedem = "Don`t forget to check out other Deals we have for you.",
	headerSaveBeaconMSG1 = "Welcome, we have a deal for you.",
	headerSaveBeaconMSG2 = "Welcome, we have a deal for you.",
	headerSaveBeaconMSG3 = "Welcome, we have a deal for you.",
	headerGetLoadingTitle = "Loading, please wait…",
	headerTxtWifiBLE = "Turn your WiFi or Bluetooth on for better performance",
	headerTxtReturn = "BACK",
	--home
	homeInicio = "HOME",
	homeEvent = "EVENTS",
	homeDeals = "DEALS",
	homeNoFilterEvent = "No upcoming events available",
	homeNoFilterDeals = "No deals available ",
	homeNoConection = "¡Connection has failed, please try again later!",
	homeNoItemsHome = "There are no Deals available at the moment",
	homeNoItemsDeals = "There are no Deals available at the moment",
	homeNoItemsEvents = "There are no Events available at this moment",
	homeMoreItems = "Explore more Deals",
	--buildRow
	buildMSGOf = "From: ",
	buildMSGSubject = "Subject",
	buildDownloads = "DOWNLOAD",
	buildDownloadeds = "DOWNLOADED",
	buildRedeemed = "REDEEMED", --
	buildShared = "SHARED",	--
	buildAvailable = " Available",
	buildHighlight = " TOP DEAL",
	--deals
	dealsTEXTA1 = "* Or turn your Bluetooth on and ask for the GO device",
	dealsTEXTA2 = "* Or ask for the GO device",
	dealsTEXTB1 = "* Turn your Bluetooth on and place your phone closer to the GO device",
	dealsTEXTB2 = "* Place your phone closer to the GO device",
	dealsTitleInfo = "Deal redeemed",
	dealsInfo = "Don’t forget to check out other deals ",
	dealsInfo2 = " we have.",
	dealstxtBtn = "DEAL REDEEMED",
	dealsTxtCode = "CODE FOR EXCHANGE",
	dealsTxtInfoRedimir  = "* Provide this code to the establishment to redeemed your Deal",
	dealsTxtRed = "CONTINUE",
	dealsTxtTitleInfoDow = "Redeemed this Deal!",
	dealsTxtInfoDow = "Keep the button pressed while near to the GO> device ",
	dealsTxtInfoDow2 = " available in all affiliated establishments. ASK FOR IT!",
	dealsTxtBtnDow = "REDEEM DEAL",
	dealsTitleInfoShare = "Deal has been shared!",
	dealstxtBtnShare = "SHARED DEAL",
	dealsTxtTotalDeals = " Deals",
	dealsTxtBtnComer = "SHARE DEAL",
	dealsTxtBtnComer2 = "GO TO ESTABLISHMENT",
	dealsTxtBtnDowCre = "DOWNLOAD DEAL",
	dealsTxtTitleInfoInterest = "¿Are you interested in this deal?",
	dealsTxtInfoWallet = "Don't think more and use it, ",
	dealsTxtInfoWallet2 = "you must be located at the establishment.",
	dealsTxtValidity = "Validty: ",
	dealsTxtAdditionalInformation = "Additional information: ",
	dealsTxtTitleInfoDS = "Shared deal",
	dealsTxtInfoDS = "Don’t forget to check out other Deals ",
	dealsTxtInfoDS2 = " we have for you.",
	dealsTxtTitleInfoTired= "We’re sorry.",
	dealsTxtInfoTired = "This deal has run out, but don’t worry",
	dealsTxtInfoTired2 = " we have more promotions for you at Go Deals!",
	dealsTxtBtnTired= "RUN OUT",
    dealsTxtClose= "Return",
    dealsTxtNear = "To redeem this deal, you must be at the establishment",
    dealsTxtUse1 = "ARE YOU SURE YO WANT",
    dealsTxtUse2 = "TO USE THIS DEAL NOW?",
    dealsTxtConfirm = "USE NOW",
    dealsTxtBtnPerfilComer = "ESTABLISHMENT PROFILE",
	--event
	eventTxtGeneralInformacion = "Additional information: ",
	--eventTxtAdditionalInformation = "Check location on map",
	eventTxtAdditionalInformation = "View on map",
	--menu
	menuTxtMenu1 = "Tutorial",
	menuTxtMenu2 = "Gift code",
	menuTxtMenu3 = "Log out",
	menuTxtMenu4 = "Affiliated establishments",
	menuTxtMenuCC = "Enter gift code",
	menuTitleLeft = "CHANGE CITY",
	menuTitleLanguageLeft = "CHANGE LANGUAGE",
	--code
	codeTextErrorCode = "* Empty field. Enter a code Gift",
	codeTxt1 = "Gift sent",
	codeTxt2 = "Check your inbox",
	codeTxtReedirCode = "Enter the code gift",
	codeTxtBtnRC = "GET GIFT",
	--friends
	friendFriendsTitle = "SHARE DEAL WITH: ",
	friendTxtRefreshFriend = "Refresf friends",
	friendTxtAceptF = "SHARE DEAL",
	friendTxtCancelF = "CANCEL",
	friendTxtSendEmailPlacer = "SEND EMAIL TO A FRIEND",
	--login
	loginNoNetworkConnection = "No network connection.",
	loginCreateAlert1 = "Email and password are required.",
	loginCreateAlert2 = "The paswords not match.",
	loginSignInAlert = "The email and password are required.",
	loginTxtReturn1 = "Back",
	loginTxtDoSignIn = "Log in",
	loginTxtReturn2 = "Back",
	loginTxtDoCreate = "Sign in",
	loginTxtCreate = "Create Account",
	loginTxtSignIn = "Sign in",
    -- login2
    loginTitle1A = "CHECK OUT ALL AVAILABLE DEALS",
    loginTitle2A = "AND DOWNLOAD THE ONE YOU LIKE.",
    loginTitle3A = "¡THEY ARE FREE BUT LIMITED!",
    loginTitle4B = "ALSO, GET ADDITIONAL GIFTS FINDING THE GIFT CODES IN",
    loginTitle5B = "THE ADVERTISING OF GO DEALS THAT YOU SEE ALONG YOUR",
    loginTitle6B = "CITY AND AFFILIATED ESTABLISHMENTS!",
    loginTitle4C = "AND CHECK OUT THE BEST EVENTS HAPPENNIG IN YOUR",
    loginTitle5C = "CITY, SO YOU ALWAYS HAVE SOMETHING NEW TO DO!",
    loginTitle6C = "",
    loginBtnFB = "LOG IN WITH FACEBOOK",
    loginBtnEmail = "JOIN WITH YOUR USERNAME OR EMAIL",
    loginBtnFree = "EXPLORE BEFORE YOU SIGN UP",
    loginFreeMessages = "HERE YOU WILL FIND ALL YOUR MESSAGES AND SPECIAL GIFTS FROM OUR AFFILIATED ESTABLISHMENTS JUST FOR YOU.",
    loginFreeDownloads = "CHECK HERE FOR ALL DEALS DOWNLOADED ¡HURRY TO GET THEM! THEY ARE LIMITED AND FOR A LIMITED TIME.",
    loginFreeGiftCode = "HERE YOU CAN ENTER ALL THE GIFT CODES YOU FIND AROUND YOUR CITY. ¡GET EXCLUSIVE DEALS WITH THEM!",
    loginFreeSign = "SIGN IN NOW!",
    loginDescUsername = "Email / Username",
    loginDescPasword = "Password",
	--mensaje
	MSGTxtPartner0 = "From: ",
	MSGTxtTitle0= "Subject: ",
	MSGxtBtnComer = "GO TO ESTABISHMENT",
	--Filter
	FilterNameEvent1 = "ALL EVENTS",
	FilterNameEvent2 = "CONCERTS",
	FilterNameEvent3 = "SPORTS",
	FilterNameEvent4 = "CULTURAL",
	FilterNameEvent5 = "ANNIVERSARIES",
	FilterNameEvent6 = "SHOPPING",
	FilterNameEvent7 = "OTHERS",
	FilterNameDeals1 = "ALL DEALS",
	FilterNameDeals2 = "RESTAURANTS",
	FilterNameDeals3 = "BARS",
	FilterNameDeals4 = "NIGHT CLUBS",
	FilterNameDeals5 = "TOURIST ACTIVITIES",
	FilterNameDeals6 = "TECHNOLOGY",
	FilterNameDeals7 = "SERVICES",
	FilterNameDeals8 = "SHOPPING",
	FilterNameDeals9 = "OTHERS",
	--[[FilterNameEvent1 = "TODOS",
	FilterNameEvent2 = "CONCIERTOS",
	FilterNameEvent3 = "DEPORTIVOS",
	FilterNameEvent4 = "CULTURALES",
	FilterNameEvent5 = "ANIVERSARIOS",
	FilterNameEvent6 = "COMPRAS",
	FilterNameEvent7 = "OTROS",
	FilterNameDeals1 = "TODOS",
	FilterNameDeals2 = "RESTAURANTES",
	FilterNameDeals3 = "BARES",
	FilterNameDeals4 = "ANTROS",
	FilterNameDeals5 = "TURISMO",
	FilterNameDeals6 = "TECNOLOGIA",
	FilterNameDeals7 = "SERVICIOS",
	FilterNameDeals8 = "COMPRAS",
	FilterNameDeals9 = "OTROS",]]
	--notifications 
	notiGetNoContent = "You haven’t any notifications yet",
	--partner
	partnerTxtInfo6 = "Available DEALS",
	--partnerWelcome
	partnerWTxtPartner0 = "¡Welcome to",
	partnerWTxtBtnComer = "VIEW MORE",
	--search
	searchTextSeparadorEventos = "Upcoming events and activities.",
	searchTextSeparadorDeals = "Promotions for you.",
	searchGetNoContent = "No results, try with another keyword",
	--wallet
	walletGetNoContent = "You haven’t downloaded any Deals yet",
	walletTextSeparadorEventos = "THESE ARE THE DEALS AVAILABLE IN YOUR WALLET.",
	walletTextSeparadorRedimir = "THESE ARE THE REDEEMED DEALS.",
	
	
}

return Language